import type { Copy } from "../lib/types";

export const copyEn: Copy = {
  nav: {
    servicos: "Services", projetos: "Projects", sites: "Websites",
    stack: "Stack", sobre: "About", faq: "FAQ", cta: 'Talk to me →',
  },
  hero: {
    eyebrow: "// Full-Stack Developer · Porto Alegre · Serving Brazil & abroad",
    h1a: "I TURN", h1b: "CODE INTO", h1c: "REAL RESULTS.",
    lead: "Websites, systems and automations for companies that want to grow without hiring more people.",
    cta1: 'DM "project" on Instagram →', cta2: "Message on WhatsApp",
    meta1: "AVAILABLE · MAY 2026", meta2: "// PORTO ALEGRE — BRAZIL", meta3: "NICOLLAS FREITAS",
    badge1: "3RD PLACE NATIONAL", badge2: "iTwin4Good BR",
  },
  services: {
    eyebrow: "// 02 — services",
    h2a: "Seven fronts.", h2b: "Zero", h2c: "runaround.",
    desc: "Price and timeline on the table before the meeting. No mystery quotes.",
    kInvest: "Investment", kPrazo: "Timeline",
    list: [
      { t: "Professional Website", d: "Complete corporate site, performant, optimized for SEO and conversion.",           price: "$500–1,600",    prazo: "7–21 days" },
      { t: "Landing Page",         d: "Single page focused on conversion. Custom copy, design and code.",                 price: "$300–1,000",    prazo: "3–10 days" },
      { t: "n8n Automation",       d: "Get people out of spreadsheets. Connect CRM, email, sheets and APIs in one flow.", price: "$400–2,400",    prazo: "5–20 days" },
      { t: "Chatbot / AI",         d: "24/7 support with a language model trained on your business.",                     price: "$500–3,000",    prazo: "7–25 days" },
      { t: "Custom Web System",    d: "CRM, light ERP, dashboards, client area. Auth + DB + API + UI.",                   price: "$1,600–6,000+", prazo: "20–90 days" },
      { t: "API Integrations",     d: "Connect your systems: ERP ↔ e-commerce, CRM ↔ marketing, bank ↔ reports.",        price: "$400–2,000",    prazo: "5–20 days" },
      { t: "Digital Consulting",   d: "Technical session to unblock projects, choose stack or audit code.",               price: "$100–600",      prazo: "2–7 days" },
    ],
  },
  projects: {
    eyebrow: "// 03 — featured projects",
    h2a: "Code that", h2b: "wins.",
    desc: "National award. Incubated startup. System in production. Automation running on its own.",
    labelProj: "PROJECT",
    list: [
      { id: "promocode", name: "PromoCode", tag: "AI Agent · WhatsApp shopping consultant", trophy: "// MVP IN PRODUCTION · N8N + AI + SUPABASE", desc: "WhatsApp shopping consultant: understands budget, use case and urgency in natural language, decides with an AI agent (LangChain + tools), remembers conversation history and learns from every recommendation via vector memory (RAG). Architecture: n8n orchestrating the agent, Chatwoot as the inbox (a human can take over any conversation at any time), Supabase with pgvector for memory, and Node.js for product search and ranking. Marketplace integration in progress." },
      { id: "haven-link", name: "Haven Link", tag: "AI · Emergency logistics", trophy: "🥉 3RD PLACE NATIONAL · iTwin4Good BR", desc: "AI platform for emergency logistics — coordinates disaster rescue, connecting volunteers, NGOs and public agencies via real-time map. Awarded nationally." },
      { id: "nexus", name: "Nexus",      tag: "Startup · CEI-UFRGS",      trophy: "🚀 INCUBATED · CEI-UFRGS",             desc: "Construction monitoring platform with applied AI. Per-site map, point-based stock control and visual detection on the construction site. Currently incubated at UFRGS Entrepreneurship Center." },
      { id: "atlas", name: "Atlas",      tag: "FGTS financial system",    trophy: "// IN PRODUCTION · FREELANCE",         desc: "Complete FGTS financial management system for a sales team. CRM for proposals, calendar, bulk queries, report exports." },
      { id: "crm-autonomo", name: "Autonomous CRM", tag: "Automation · Lead generation", trophy: "// IN PRODUCTION · OWN SYSTEM", desc: "Prospecting engine that scans the map by category and city, identifies businesses without a website, and creates the deal + follow-up task straight in the CRM — zero manual clicks, zero API cost." },
    ],
  },
  sites: {
    eyebrow: "// 04 — websites delivered",
    h2a: "Live.", h2b: "Selling.",
    desc: "Clients across different sectors. Common denominator: fast site, honest copy, measured conversion.",
  },
  ventures: {
    eyebrow: "// 05 — my ventures",
    h2a: "Not just dev.", h2b: "Founder.",
    desc: "Two companies I co-founded. Where I'm CEO alongside my partners.",
    labelRole: "CEO & CO-FOUNDER",
    cta: "visit site →",
    list: [
      { n: "Codaryn", tag: "Digital solutions", url: "codaryn.com.br", desc: "Digital solutions company for your business. We apply technologies that simplify challenges and amplify results — full team of developers, support and administration.", tags: ["Full team", "Support", "Applied tech"] },
      { n: "Nexium",  tag: "AI construction monitoring", url: "nexusbrtech.com", desc: "Construction monitoring platform with applied AI. Per-site map, point-based stock control and visual detection on the construction site. Incubated at CEI-UFRGS.", tags: ["Applied AI", "CEI-UFRGS incubated", "Real-time map"] },
    ],
  },
  stack: {
    eyebrow: "// 06 — tech stack",
    h2a: "A tool", h2b: "is not a faith.",
    desc1: "I pick the stack based on the client's problem, not the dev's taste.",
    desc2: "But, in general, this is the lineup:",
  },
  about: {
    eyebrow: "// 07 — about",
    proofEyebrow: "// credentials",
    sub: "NICOLLAS FREITAS · POA",
    h3a: "An engineer who", h3b: "codes.",
    bio1a: "Computer Science student at ", bio1b: "Unisinos + UERGS", bio1c: ", fullstack dev and former intern at the ", bio1d: "Federal Police in digital forensics", bio1e: ".",
    bio2: "Today I serve SMBs and local businesses across Brazil as a solo dev. Focus on shipping things that go to production and make money — not portfolio vitrine.",
    a1h1: "3rd", a1h2: "nationally", a1d: "iTwin4Good BR",
    a2h1: "Incubated", a2h2: "startup", a2d: "CEI-UFRGS",
    a3h1: "Digital", a3h2: "forensics", a3d: "Internship · Federal Police",
  },
  certificates: {
    eyebrow: "// 08 — certificates",
    h2a: "Always", h2b: "learning.",
    desc: "Technical certifications from recognized courses and platforms.",
    kBadge: "Certified", kDate: "Completed", kDuration: "Duration", kId: "ID",
    list: [
      {
        provider: "Google Cloud",
        title: "Google SecOps Foundation",
        issuer: "ARKI1 · Latin America Training Partner of the Year",
        date: "Jun 9, 2026",
        duration: "3h",
        id: "P-SF+V+2026-06-09_8694088B",
      },
    ],
  },
  faq: {
    eyebrow: "// 09 — frequently asked questions",
    h2a: "Before", h2b: "booking a call.",
    list: [
      { q: "What is the average timeline for a website?",         a: "Landing page: 3–10 days. Corporate site: 7–21 days. Custom system: 20+ days. I send a milestone schedule before starting." },
      { q: "Do you offer maintenance after delivery?",            a: "Yes. Monthly SLA (fixes, small evolutions, monitoring) or hourly billing. Your choice." },
      { q: "Do I need to have a domain and hosting?",             a: "You don't need to — I handle setup. If you have one, great, we migrate. If not, I help you buy with proper invoicing." },
      { q: "Do you serve clients outside Rio Grande do Sul?",     a: "Yes. I work with clients all over Brazil 100% remotely. Meetings via Meet/Zoom, weekly deliveries." },
      { q: "How does payment work?",                              a: "50% upfront + 50% on delivery for short projects. For long projects, milestone-based. PIX, bank slip or card (with fee)." },
      { q: "What is n8n automation?",                             a: "n8n is a tool that connects your systems (CRM, email, spreadsheet, WhatsApp, ERP) in a single flow. Ex.: client fills form → enters CRM → triggers email → creates proposal. Removes humans from repetitive tasks." },
      { q: "Difference between landing page and corporate site?", a: "Landing page is a single page focused on ONE conversion (lead, sale, booking). Corporate site has multiple pages (home, about, services, blog, contact) and exists for brand presence + SEO." },
    ],
  },
  finalCta: {
    eyebrow: "// start now",
    h2a: "Ready to", h2b: "transform", h2c: "your business?",
    lead: "Tell me your problem. In 5 minutes I'll tell you the best path.",
    cta1: 'DM "project" on Instagram →', cta2: "Message on WhatsApp",
    ig: 'DM with the word "PROJECT"',
  },
  contact: {
    eyebrow: "// 10 — contact",
    h2a: "Let's", h2b: "talk.",
    desc: "Pick the channel you use most. I usually reply within 24h on weekdays.",
    cards: [
      { k: "WhatsApp",  v: "+55 51 3199-9319",             sub: "Reply < 24h",           hint: "open chat →",       href: "https://wa.me/555131999319?text=Hello%21%20I%20want%20to%20start%20a%20project%21" },
      { k: "Instagram", v: "@dev_mitolenda",         sub: "DM 'project'",          hint: "open profile →",    href: "https://instagram.com/dev_mitolenda" },
      { k: "Email",     v: "devmitolenda@gmail.com", tech: 1, sub: "Detailed brief",       hint: "compose email →",   href: "mailto:devmitolenda@gmail.com" },
      { k: "LinkedIn",  v: "in/nicollasde",          tech: 1, sub: "Professional profile", hint: "open linkedin →",   href: "https://linkedin.com/in/nicollasde" },
    ],
  },
  footer: {
    inicio: "home", servicos: "services", projetos: "projects",
    sobre: "about", faq: "faq", contato: "contact",
  },
};
